### PR TITLE
Adds Cube test

### PR DESCRIPTION
**Pull request by lordofthejars**
I have added a simple integration test using Arquillian Cube. I don't know if you were thinking on a functional test, or this is enough

### CODE REVIEW

**Comment by lordofthejars** [comment]
It should work with Boot2Docker without any change.

**Comment by arun-gupta** [comment]
Will try and let you know.

**Comment by lordofthejars** [comment]
Also Aslak is working in Chamaleon extension, if he finishes before Monday I will add it on the example too.

**Comment by arun-gupta** [comment]
sounds good

**Comment by arun-gupta** [comment]
@lordofthejars getting the following error when doing `mvn package`:

```
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ javaee-arquillian-cube ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/arungupta/workspaces/javaee-arquillian-cube/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[8,47] package org.jboss.arquillian.container.test.api does not exist
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[9,34] package org.jboss.arquillian.junit does not exist
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[10,32] package org.jboss.shrinkwrap.api does not exist
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[11,38] package org.jboss.shrinkwrap.api.asset does not exist
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[12,37] package org.jboss.shrinkwrap.api.spec does not exist
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[20,19] cannot find symbol
  symbol:   class WebArchive
  location: class org.javaee7.sample.PersonDatabaseTest
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[16,10] cannot find symbol
  symbol: class Arquillian
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[19,6] cannot find symbol
  symbol:   class Deployment
  location: class org.javaee7.sample.PersonDatabaseTest
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[23,38] cannot find symbol
  symbol:   variable EmptyAsset
  location: class org.javaee7.sample.PersonDatabaseTest
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[21,34] cannot find symbol
  symbol:   class WebArchive
  location: class org.javaee7.sample.PersonDatabaseTest
[ERROR] /Users/arungupta/workspaces/javaee-arquillian-cube/src/test/java/org/javaee7/sample/PersonDatabaseTest.java:[21,16] cannot find symbol
  symbol:   variable ShrinkWrap
  location: class org.javaee7.sample.PersonDatabaseTest
[INFO] 11 errors 
```

Will continue to fix it.

**Comment by arun-gupta** [comment]
This need to work with docker-machine and currently gives the following error:

```
Caused by: java.lang.IllegalArgumentException: Boot2Docker command does not return a valid ip. It returned error in run: VM "boot2docker-vm" is not running..
    at org.arquillian.cube.impl.util.Boot2Docker.getIp(Boot2Docker.java:39)
    at org.arquillian.cube.impl.util.Boot2Docker.ip(Boot2Docker.java:25)
    at org.arquillian.cube.impl.client.CubeConfigurator.resolveBoot2Docker(CubeConfigurator.java:61)
    at org.arquillian.cube.impl.client.CubeConfigurator.resolveServerIp(CubeConfigurator.java:46)
    at org.arquillian.cube.impl.client.CubeConfigurator.configure(CubeConfigurator.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

@lordofthejars any chance you can fix this on Tuesday. If so, then I can include this in DevoxxUK lab.

**Comment by lordofthejars** [comment]
The compilation error I think it is because Arquillian is inside Cube Maven profile. So if it is not activated (with -P option) Arquillian dependencies are not in classpath and it fails. Probably you have already fix it.

About second error, the problem is that it seems that boot2docker is not running on the machine you are executing. In cube we already detect if the example is running on Windows or MacOS and then we try to execute the program `boot2docker ip` to get the ip of boot2docker. But instead of returning IP it says `VM "boot2docker-vm" is not running` so probably the problem is that boot2docker is not up and running or it is not in your PATH variable.

You can do three things:
- Put boot2docker in PATH
- User serverUri Cube parameter setting the boot2docker vm ip (_http(s)://.....)
- Set boot2docker installation directory using _ boot2dockerPath_ parameter

For me the easiest way is by using PATH variable so configuration file looks much clear.
Let me know if this has fixed the error.

**Comment by arun-gupta** [comment]
`mvn package -Pcube` fixed the compilation error but gave:

```
java.lang.annotation.IncompleteAnnotationException: org.junit.runner.RunWith missing element value
    at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:80)
    at com.sun.proxy.$Proxy2.value(Unknown Source)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
```

Multiple instances of Docker Host can be configured using docker-machine and so boot2docker becomes an implementation detail. Can you add an example of serverUri in `pom.xml`?

**Comment by lordofthejars** [comment]
Don't know about this exception. I have seen that I missed junit scope and not it is with the default one and it should be test, maybe it takes some conflict with scopes. Also try to put it inside profile. Currently I have no computer  to try it :).

For serverUri you should do something like:
<property name="serverUri">https://boot2docker:2376</property>

where boot2docker is the ip returned by boot2docker ip call.

**Comment by arun-gupta** [comment]
Where does this serverUri need to be specified? In arquillian.xml?

In extension? As a property?

Arun

**Comment by lordofthejars** [comment]
yes in arquillian.xml

```
<extension qualifier="docker"> 
      <property name="serverVersion">1.12</property> 
      <property name="serverUri">https://boot2docker:2376</property> 
      <property name="dockerContainers"> 

      </property>
  </extension>
```

**Comment by arun-gupta** [comment]
This is now working.

So a new container is created for every run? And completely destroyed after the tests are run?

Is there an option to keep the container so that I can investigate the logs afterwards?

Does the Dockerfile must be specified or can I specify a pre-built image?

Arun

**Comment by lordofthejars** [comment]
it can be use a pre-built image with _image_ attribute instead of _buildImage_:

```
<property name="dockerContainers"> (4)
          tomcat:
            image: tutum/tomcat:7.0
```

About logs you have two options, the first one is getting the logs to a file as described here: https://github.com/arquillian/arquillian-cube#before-stop-events

The other option is as you said to not stop the container and reuse it in each run. You can read here about these options: https://github.com/arquillian/arquillian-cube#allow-connecting-to-a-running-container

**Comment by arun-gupta** [comment]
So use:

```
            wildfly:
              image: jboss/wildfly
```

instead of:

```
            wildfly:
              buildImage:
                dockerfileLocation: src/test/resources/wildfly
                noCache: true
                remove: true
```

?

**Comment by lordofthejars** [comment]
exactly, but the image should be prepared to deploy a file from remote. So probably you will need something like:

```
RUN /opt/jboss/wildfly/bin/add-user.sh -up mgmt-users.properties admin Admin#70365 --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
```

**Comment by arun-gupta** [comment]
Details specified at: https://github.com/javaee-samples/docker-java/blob/master/chapters/docker-testing.adoc

Let me know if anything needs to be improved.

**Comment by lordofthejars** [comment]
Perfect :+1: of course it is not so extensive, but it covers the basics and with source code I am sure that everyone will understand exactly the purpose.

BTW do you think we would need to implement docker-machine integration too for getting the IP as we are doing in boot2docker?

**Comment by arun-gupta** [comment]
Thanks, this is only the first version. Feel free to send a PR for any other material that you'd like to cover :)

Yes, docker machine is the way to host multiple docker hosts on Mac and Windows and should be integrated.

**Comment by lordofthejars** [comment]
ok I will see how it works and how it can be integrated. Thanks for your comments and probably I will update the example with docker-compose example when I finish to implement its support on Cube.

**Comment by arun-gupta** [comment]
Learn about Docker Machine from: http://blog.arungupta.me/docker-machine-seutp-docker-host-techtip78/

**Pull request merged**
